config/routes.rb
Rails.application.routes.draw do
  root 'cuisines#index'
 resources :foods
 resources :cuisines do
 resources :dishes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
	has_many :dishes
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :cuisine 
  has_many :food_dishes
  has_many :foods, through: :food_dishes
end

app/models/food.rb
class Food < ApplicationRecord
	has_many :food_dishes
  	has_many :dishes, through: :food_dishes
end

app/models/food_dish.rb
class FoodDish < ApplicationRecord
  belongs_to :food
  belongs_to :dish
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def index
  	@cuisines=Cuisine.all
  end
  def create
  	@cuisine=Cuisine.new
  	@cuisine.name = params[:cuisine][:name]
  	@cuisine.save
  	redirect_to cuisines_url
  end
  def new
  	@cuisine=Cuisine.new
  end
  def edit
  	@cuisine=Cuisine.find(params[:id])
  end
  def update
   @cuisine=Cuisine.find(params[:id])
   @cuisine.name = params[:cuisine][:name]
      @cuisine.save
   redirect_to cuisines_url
 end
 
 def destroy
   @cuisine=Cuisine.find(params[:id])
   @cuisine.destroy
   redirect_to cuisines_url
 end
 def show
   @cuisine=Cuisine.find(params[:id])
   @dishes=@cuisine.dishes
   @dish=@cuisine.dishes.build
 end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def index
    @cuisine=Cuisine.find(params[:cuisine_id])
   @dishes=@cuisine.dishes
   @dish=@cuisine.dishes.build
     end
  def create
    @cuisine=Cuisine.find(params[:cuisine_id])
  	m=@cuisine.dishes.build
  	m.name = params[:dish][:name]
  	m.save
  	redirect_to cuisine_url(id:@cuisine.id)
  end
  def new
  	@cuisine=Cuisine.find(params[:cuisine_id])
   @dishes=@cuisine.dishes
   @dish=@cuisine.dishes.build
     end
  def edit
  @cuisine=Cuisine.find(params[:cuisine_id])
   @dishes=@cuisine.dishes
   @dish=@dishes.find(params[:id])
  	end
  def update
   @cuisine=Cuisine.find(params[:cuisine_id])
   @dishes=@cuisine.dishes
   @dish=@cuisine.dishes.build
   @dish=@dishes.find(params[:id])
   @dish.name = params[:dish][:name]
      @dish.save
   redirect_to cuisine_dishes_url
 end
 
 def destroy
   @cuisine=Cuisine.find(params[:cuisine_id])
   @dishes=@cuisine.dishes
   @dish=@cuisine.dishes.build
   @dish=@dishes.find(params[:id])
   @dish.destroy
  redirect_to cuisine_dishes_url
 end
 def show
    @cuisine=Cuisine.find(params[:cuisine_id])
   @dishes=@cuisine.dishes
   @dish=@cuisine.dishes.build
   @dish=@dishes.find(params[:id])
 end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
  	@m=Food.all
  end
  def create
  	m=Food.new
  	m.name = params[:food][:name]
  	m.veg = params[:food][:veg]
  	m.category = params[:food][:category]
  	m.save
  	redirect_to foods_url
  end
  def new
  	@m=Food.new
  end
  def edit
  	@m=Food.find(params[:id])
  end
def update
	@m=Food.find(params[:id])
	@m.name = params[:food][:name]
  	@m.veg = params[:food][:veg]
  	@m.category = params[:food][:category]
  	@m.save
  	redirect_to foods_url
end
 
  def destroy
  	@m=Food.find(params[:id])
  	@m.destroy
  	redirect_to foods_url
  end
   def show
  	@m=Food.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/cuisines/_cuisineform.html.erb
<%=form_for @cuisine do |x| %>
<p>
	<%=x.label :name%> 
	<%=x.text_field :name%> <br>
		<%= x.submit "submit"%>
</p>
<%end%>
<%= link_to 'back' , cuisines_url %>

app/views/cuisines/edit.html.erb
<h3 style="text-align:center;"> Edit Cuisines </h3>
<%= render partial: "cuisineform" %>

app/views/cuisines/index.html.erb
<h3 style="text-align:center;"> Cuisines </h3>
<table>
	<% @cuisines.each do |cuisine| %>
	<tr><td>NAME:</td>
<td><%= cuisine.name%></td> 
	<td><%=link_to 'edit',edit_cuisine_url(id:cuisine.id)%></td>
	<td><%=link_to 'show',cuisine_url(id:cuisine.id)%></td>
	<td><%=link_to 'destroy',cuisine_url(id:cuisine.id), method: :delete%></td>
</tr>
<%end%>
</table>
<%=link_to 'new',new_cuisine_url%>

app/views/cuisines/new.html.erb
<h3 style="text-align:center;"> New Cuisine </h3>
<%= render partial: "cuisineform" %>

app/views/cuisines/show.html.erb
<h3 style="text-align:center;"> Cuisine </h3>
<table>
<tr><td>NAME:</td>
<td><%= @cuisine.name%></td></tr> 
</table>
<%=form_for [@cuisine, @dish] do |x| %>
<p>
	<%=x.label :name%> 
	<%=x.text_field :name%> <br>
		<%= x.submit "submit"%>
</p>
<%end%>
<table>
	<% @dishes.each do |dish| %>
		<% if dish.persisted? %>
			<tr>
				<td>NAME:</td> 
				<td><%= dish.name%></td>
				<td><%= link_to 'Edit', edit_cuisine_dish_url(@cuisine.id,dish.id) %></td>
				<td><%=link_to 'show',cuisine_dish_url(@cuisine.id,dish.id)%></td>
				<td><%=link_to 'delete',cuisine_dish_url(@cuisine.id,dish.id), method: :delete%></td>
				  
			</tr>
		<%end%>
	<%end%>
</table>

<%=link_to 'back',cuisines_url%>

app/views/dishes/_dishform.html.erb
<%=form_for [@cuisine, @dish] do |x| %>
<p>
	<%=x.label :name%> 
	<%=x.text_field :name%> <br>
		<%= x.submit "submit"%>
</p>
<%end%>

app/views/dishes/edit.html.erb
<h3 style="text-align:center;"> Edit Dish </h3>
<%= render partial: "dishform" %>

app/views/dishes/index.html.erb
<h3 style="text-align:center;"> Dishes </h3>
<table>
	<% @dishes.each do |dish| %>
	<% if dish.persisted? %>
	<tr><td>NAME:</td> 
<td><%= dish.name%></td>
<td><%=link_to 'edit',edit_cuisine_dish_url(id:dish.id)%></td>
<td><%=link_to 'delete',cuisine_dish_url(id:dish.id), method: :delete%></td>
<td><%=link_to 'show',cuisine_dish_url(id:dish.id)%></td>
</tr> <%end%><%end%>
</table>
<%=link_to 'new',new_cuisine_dish_url(id:@dish.id)%>

app/views/dishes/new.html.erb
<h3 style="text-align:center;"> New Dish </h3>
<%= render partial: "dishform" %>

app/views/dishes/show.html.erb
<h3 style="text-align:center;"> Dish </h3>
	<% if @dish.persisted? %>
	<p>NAME:
	<%= @dish.name%></br></p><%end%>

app/views/foods/_foodform.html.erb
<%=form_for @m do |x| %>
<p>
	<%=x.label :name%> 
	<%=x.text_field :name%> <br>
	<%=x.label :veg %> 
	<%=x.check_box :veg ,{},'true'%><br>
	<%= x.label :category%>
    <%= x.radio_button :category, "Vegetables and legumes/beans" %> Vegetables and legumes/beans
    <%= x.radio_button :category, "Fruit " %> Fruit 
    <%= x.radio_button :category, "Grains" %> Grains
     <%= x.radio_button :category, "Meat" %> Meat
      <%= x.radio_button :category, "Dairy product" %> Dairy product<br />
	<%= x.submit "submit"%>
</p>
<%end%>

app/views/foods/edit.html.erb
<%= render partial: "foodform" %>

app/views/foods/index.html.erb
<table>
	<% @m.each do |food| %>
	<tr><td>NAME:</td>
<td><%= food.name%></td> 
<td>ISVEG:</td>
	<td><%=food.veg %></td>
<td>CATEGORY</td>
	<td><%= food.category %></td>
	<td><%=link_to 'edit',edit_food_url(id:food.id)%></td>
	<td><%=link_to 'show',food_url(id:food.id)%></td>
	<td><%=link_to 'destroy',food_url(id:food.id), method: :delete%></td>
</tr>
<%end%>
</table>
<%=link_to 'new',new_food_url%>

app/views/foods/new.html.erb
<%= render partial: "foodform" %>

app/views/foods/show.html.erb
<table>
<tr><td>NAME:</td>
<td><%= @m.name%></td> 
<td>ISVEG:</td>
	<td><%=@m.veg %></td>
<td>CATEGORY</td>
	<td><%= @m.category %></td></tr>
	</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Menu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>